server:
  port: ${PORT:8080}

spring:
  h2:
    console:
      enabled: true
  mvc:
    static-path-pattern: /**
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASS:12345}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update